'use client';

import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';

type Row = Record<string, unknown>;
type Prospect = { id: string; name: string; company?: string; role?: string; phone?: string; source?: string; fit?: string; status?: string; qualification?: unknown; phone_status?: string; contact_id?: string };
type Brief = { principal_name: string; offer: string; audience: string; geography: string; exclusions: string; claims: string; timezone: string; booking_link: string; budget_usd: number };
type Report = { mode: 'simulation' | 'live'; brief: Brief | null; brief_revision: number; prospects: Prospect[]; messages: { id: string; prospect_id: string; direction: string; text: string; simulated: boolean; created_at: string }[]; decisions: { id: string; prospect_id: string; purpose: string; text: string; status: string; revision?: string }[]; jobs: Row[]; metrics: Row; readiness: Row; events: Row[] };
const emptyBrief: Brief = { principal_name: '', offer: '', audience: '', geography: '', exclusions: '', claims: '', timezone: 'Africa/Johannesburg', booking_link: '', budget_usd: 0 };
const input = 'w-full rounded-md border bg-background px-3 py-2 text-sm';
const button = 'rounded-md border px-3 py-2 text-sm font-medium hover:bg-muted disabled:opacity-50';
const panel = 'space-y-4 rounded-xl border bg-card p-5';
const display = (value: unknown) => typeof value === 'string' ? value : JSON.stringify(value ?? null);

export function DogfoodWorkspace() {
  const [report, setReport] = useState<Report | null>(null);
  const [brief, setBrief] = useState<Brief>(emptyBrief);
  const [tab, setTab] = useState('Brief');
  const [selected, setSelected] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [reply, setReply] = useState('');
  const [reason, setReason] = useState('');
  const [source, setSource] = useState('fixture');
  const [limit, setLimit] = useState(10);
  const [phone, setPhone] = useState('');
  const [evidence, setEvidence] = useState('');
  const [party, setParty] = useState('recipient');
  const [scope, setScope] = useState('contact');
  const [start, setStart] = useState('');
  const [end, setEnd] = useState('');
  const [minutes, setMinutes] = useState(0);
  const [note, setNote] = useState('');
  const [useful, setUseful] = useState(true);
  const initialized = useRef(false);
  const pending = useRef(false);
  const refresh = useCallback(async () => {
    const response = await fetch('/api/concierge/dogfood', { cache: 'no-store' });
    const data = await response.json();
    if (!response.ok) throw new Error(data.error || 'Workspace could not be loaded.');
    if (!['simulation', 'live'].includes(data.mode) || !Array.isArray(data.prospects) || !Array.isArray(data.messages) || !Array.isArray(data.decisions)) throw new Error('The service returned an incomplete workspace.');
    setReport(data);
    if (!initialized.current) { setBrief({ ...emptyBrief, ...data.brief }); initialized.current = true; }
  }, []);
  useEffect(() => { void refresh().catch(e => setError(e.message)); }, [refresh]);
  async function act(command: string, fields: Row = {}) {
    if (pending.current) return false;
    pending.current = true; setBusy(true); setError(''); setNotice('');
    try {
      const response = await fetch('/api/concierge/dogfood', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ command, ...fields }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || 'Action failed.');
      try { await refresh(); } catch { throw new Error('The action completed, but the workspace could not refresh. Refresh before repeating it.'); }
      setNotice('Workspace updated.');
      return true;
    } catch (e) { setError(e instanceof Error ? e.message : 'Action failed. Refresh before retrying.'); return false; }
    finally { pending.current = false; setBusy(false); }
  }
  const prospect = report?.prospects.find(p => p.id === selected);
  const simulation = report?.mode === 'simulation';
  const selectedFields = { prospect_id: selected };
  return <main className="mx-auto max-w-6xl space-y-6 p-4 md:p-8">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Chris · Outbound dogfood</h1><p className="text-sm text-muted-foreground">Brief → find people → converse → introduce → measure.</p></div><button className={button} disabled={busy} onClick={() => void refresh().catch(e => setError(e.message))}>Refresh</button></div>
    <div className="rounded-lg border p-3 text-sm">{report ? simulation ? 'Simulation: messages and calendar effects stay local. Fixture results are fictional; real research and model calls may incur configured costs.' : 'Live workspace: review and prepare here. This screen does not execute external messages or calendar invitations.' : 'Connecting to your workspace…'}</div>
    {error && <div role="alert" className="rounded-lg border border-destructive p-3 text-sm">{error}</div>}
    {notice && <p role="status" className="text-sm">{notice}</p>}
    <nav aria-label="Dogfood workflow" className="flex flex-wrap gap-2">{['Brief', 'Prospects', 'Conversation', 'Review', 'Connections & pilot'].map(name => <button key={name} className={`${button} ${tab === name ? 'bg-muted' : ''}`} aria-current={tab === name ? 'page' : undefined} onClick={() => setTab(name)}>{name}</button>)}</nav>
    {tab === 'Brief' && <form className={panel} onSubmit={e => { e.preventDefault(); void act('save_brief', { brief }); }}>
      <h2 className="text-lg font-semibold">Your outbound brief</h2><p className="text-sm text-muted-foreground">Use one offer, audience and geography. Saving a revision may invalidate queued work. Budget 0 keeps paid work blocked.</p>
      {(['principal_name', 'offer', 'audience', 'geography', 'exclusions', 'claims', 'timezone', 'booking_link'] as const).map(key => <label key={key} className="block space-y-1 text-sm"><span>{({ principal_name: 'Your name', offer: 'What you offer', audience: 'Who Chris should find', geography: 'Geography', exclusions: 'Exclusions and existing relationships', claims: 'Supported claims and evidence', timezone: 'Your timezone', booking_link: 'Booking link (optional)' })[key]}</span><textarea className={input} rows={['offer', 'audience', 'claims'].includes(key) ? 3 : 1} value={brief[key]} onChange={e => setBrief({ ...brief, [key]: e.target.value })} required={!['exclusions', 'claims', 'booking_link'].includes(key)} /></label>)}
      <label className="block text-sm">Research and model budget (USD)<input className={input} type="number" min="0" max="10000" step="0.01" value={brief.budget_usd} onChange={e => setBrief({ ...brief, budget_usd: Number(e.target.value) })} /></label>
      <button className={button} disabled={busy || !report}>Save brief</button><span className="ml-3 text-sm text-muted-foreground">Saved revision: {report?.brief_revision ?? 0}</span>
    </form>}
    {tab === 'Prospects' && <div className="space-y-5"><section className={panel}><h2 className="text-lg font-semibold">Find and qualify people</h2><div className="flex flex-wrap gap-3"><label className="text-sm">Source<select className={input} value={source} onChange={e => setSource(e.target.value)}><option value="fixture">Fictional fixtures (no research spend)</option><option value="treg">Real research (configured treg provider)</option></select></label><label className="text-sm">Candidates<input className={input} type="number" min="1" max="20" value={limit} onChange={e => setLimit(Number(e.target.value))} /></label><button className={button} disabled={busy || !report?.brief} onClick={() => void act('discover', { source, limit })}>Find candidates</button><button className={button} disabled={busy || !report} onClick={() => void act('process')}>Process queued work</button></div><p className="text-sm text-muted-foreground">A profile or phone number does not establish permission to contact. Missing numbers stay visible.</p></section>
      <div className="grid gap-4 md:grid-cols-2">{report?.prospects.map(p => <button key={p.id} className={`${panel} text-left ${selected === p.id ? 'ring-2 ring-primary' : ''}`} onClick={() => { setSelected(p.id); setPhone(p.phone || ''); }}><h3 className="font-semibold">{p.name}</h3><p className="text-sm">{[p.role, p.company].filter(Boolean).join(' · ')}</p><p className="text-sm">{p.fit || 'Fit needs review'}</p><p className="break-words text-xs text-muted-foreground">Source: {p.source || 'No source'}<br />Status: {p.status} · {p.phone_status || 'Phone unresolved'}<br />{p.phone || 'No phone found'}</p></button>)}</div>
      {!report?.prospects.length && <p className="text-sm">Save a brief, then find the first candidates.</p>}
      {prospect && <section className={panel}><h3 className="font-semibold">Review {prospect.name}</h3><p className="break-words text-sm">Qualification: {display(prospect.qualification)}</p><label className="block text-sm">Reason<textarea className={input} value={reason} onChange={e => setReason(e.target.value)} /></label><div className="flex gap-2">{['qualified', 'rejected'].map(verdict => <button key={verdict} className={button} disabled={busy || !reason.trim()} onClick={() => void act('qualify', { ...selectedFields, verdict, reason })}>{verdict === 'qualified' ? 'Qualify' : 'Reject'}</button>)}</div><label className="block text-sm">International phone<input className={input} value={phone} onChange={e => setPhone(e.target.value)} placeholder="+…" /></label><label className="block text-sm">Evidence linking this number to the person<textarea className={input} value={evidence} onChange={e => setEvidence(e.target.value)} /></label><div className="flex flex-wrap gap-2"><button className={button} disabled={busy || !phone || !evidence.trim()} onClick={() => void act('enrich', { ...selectedFields, phone, source_ref: evidence })}>Record contact evidence</button><button className={button} disabled={busy || !prospect.phone} onClick={() => void act('promote', selectedFields)}>Save qualified person to CRM</button><button className={button} onClick={() => setTab('Conversation')}>Open conversation</button></div></section>}
    </div>}
    {tab === 'Conversation' && <div className="space-y-5"><section className={panel}><h2 className="text-lg font-semibold">{simulation ? 'Play the recipient' : 'Conversation preparation'}</h2><label className="block text-sm">Person<select className={input} value={selected} onChange={e => setSelected(e.target.value)}><option value="">Choose a prospect</option>{report?.prospects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="flex flex-wrap gap-2"><button className={button} disabled={busy || !selected} onClick={() => void act('start', selectedFields)}>Let Chris initiate</button><button className={button} disabled={busy || !selected} onClick={() => void act('takeover', selectedFields)}>Take over</button><button className={button} disabled={busy || !selected} onClick={() => void act('resume', selectedFields)}>Resume Chris</button><button className={button} disabled={busy || !report} onClick={() => void act('process')}>Process queued work</button></div><p className="text-sm text-muted-foreground">Model: {display(report?.readiness?.model ?? 'Check connection status')}. Review prepared actions below. Taking over pauses Chris.</p></section>
      <section className={panel} aria-label="Conversation messages">{report?.messages.filter(m => m.prospect_id === selected).map(m => <article key={m.id} className={`max-w-[90%] rounded-lg border p-3 ${['outbound', 'out'].includes(m.direction) ? 'ml-auto bg-muted' : ''}`}><p className="text-xs text-muted-foreground">{['outbound', 'out'].includes(m.direction) ? 'Chris' : prospect?.name || 'Recipient'} · {m.simulated ? 'simulated' : 'provider record'} · {m.created_at}</p><p className="whitespace-pre-wrap text-sm">{m.text}</p></article>)}{simulation && <form onSubmit={e => { e.preventDefault(); void act('reply', { ...selectedFields, text: reply }).then(ok => { if (ok) setReply(''); }); }}><label className="block text-sm">Type as the recipient<textarea className={input} value={reply} onChange={e => setReply(e.target.value)} /></label><button className={`${button} mt-2`} disabled={busy || !selected || !reply.trim()}>Add recipient reply</button></form>}</section>
      <section className={panel}><h3 className="font-semibold">Permission and introduction</h3><p className="text-sm text-muted-foreground">Record what each party actually agreed to, with its source. This is an attestation, not inferred permission.</p><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Party<select className={input} value={party} onChange={e => setParty(e.target.value)}><option value="recipient">Recipient</option><option value="principal">You</option></select></label><label className="text-sm">Permission<select className={input} value={scope} onChange={e => setScope(e.target.value)}>{['contact', 'introduction', 'group', 'scheduling', 'booking'].map(s => <option key={s}>{s}</option>)}</select></label></div><label className="block text-sm">Supporting message or evidence<textarea className={input} value={evidence} onChange={e => setEvidence(e.target.value)} /></label><button className={button} disabled={busy || !selected || !evidence.trim()} onClick={() => void act('consent', { ...selectedFields, party, scope, source_ref: evidence })}>Record permission</button><button className={`${button} ml-2`} disabled={busy || !selected} onClick={() => void act('introduce', selectedFields)}>Prepare introduction</button></section>
      <section className={panel}><h3 className="font-semibold">Meeting proposal</h3><p className="text-sm text-muted-foreground">Use ISO timestamps with offsets, for example 2026-10-01T10:00:00+02:00. A prepared proposal is not a booked meeting.</p><label className="block text-sm">Start<input className={input} value={start} onChange={e => setStart(e.target.value)} /></label><label className="block text-sm">End<input className={input} value={end} onChange={e => setEnd(e.target.value)} /></label><button className={button} disabled={busy || !selected || !start || !end} onClick={() => void act('propose', { ...selectedFields, start, end, timezone: brief.timezone })}>Prepare time proposal</button><button className={`${button} ml-2`} disabled={busy || !selected || !start || !end} onClick={() => void act('book', { ...selectedFields, start, end })}>Prepare booking</button></section>
    </div>}
    {(tab === 'Conversation' || tab === 'Review') && <section className={panel}><h2 className="text-lg font-semibold">Action review</h2>{report?.decisions.filter(d => tab === 'Review' || d.prospect_id === selected).map(d => <article key={d.id} className="space-y-2 rounded-lg border p-3"><p className="text-sm font-medium">{report.prospects.find(p => p.id === d.prospect_id)?.name || d.prospect_id} · {d.purpose} · {d.status}</p><p className="whitespace-pre-wrap text-sm">{d.text}</p>{['pending', 'prepared', 'proposed', 'awaiting_review'].includes(d.status) && <div className="flex gap-2"><button className={button} disabled={busy || !simulation} onClick={() => void act('approve', { decision_id: d.id })}>{simulation ? 'Approve in simulation' : 'Live execution unavailable here'}</button><button className={button} disabled={busy} onClick={() => void act('discard', { decision_id: d.id })}>Discard</button></div>}</article>)}{!report?.decisions.length && <p className="text-sm text-muted-foreground">Chris’s proposed actions appear here.</p>}</section>}
    {tab === 'Review' && <section className={panel}><h2 className="text-lg font-semibold">Your effort and judgment</h2><label className="block text-sm">Prospect<select className={input} value={selected} onChange={e => setSelected(e.target.value)}><option value="">Choose a prospect</option>{report?.prospects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={useful} onChange={e => setUseful(e.target.checked)} />This opportunity was useful</label><label className="block text-sm">Your minutes spent<input className={input} type="number" min="0" max="1440" value={minutes} onChange={e => setMinutes(Number(e.target.value))} /></label><label className="block text-sm">Corrections, intervention and outcome<textarea className={input} value={note} onChange={e => setNote(e.target.value)} /></label><button className={button} disabled={busy || !selected} onClick={() => void act('review', { ...selectedFields, useful, minutes, note })}>Record review</button></section>}
    {tab === 'Connections & pilot' && <div className="space-y-5"><section className={panel}><h2 className="text-lg font-semibold">Wabi → WhatsApp → Unipile → Chris</h2><p className="text-sm">Obtain and retain your Wabi number, register its WhatsApp account, then link that account to Unipile. Verify Chris’s identity and a controlled round-trip before approaching prospects.</p><p className="text-sm">The experiment starts with controlled participants, then a proposed first wave of 5 qualified prospects and up to 20 total after review. Provider configuration alone is not live acceptance.</p><button className={button} disabled={busy || !report} onClick={() => void act('readiness')}>Check readiness</button><Link className="ml-3 text-sm underline" href="/contacts">CRM contacts</Link><dl className="grid gap-3 sm:grid-cols-2">{Object.entries(report?.readiness ?? {}).map(([key, value]) => <div key={key} className="rounded-md border p-3"><dt className="text-xs text-muted-foreground">{key.replaceAll('_', ' ')}</dt><dd className="break-words text-sm">{display(value)}</dd></div>)}</dl></section><section className={panel}><h2 className="text-lg font-semibold">Pilot measures</h2><dl className="grid gap-3 sm:grid-cols-3">{Object.entries(report?.metrics ?? {}).map(([key, value]) => <div key={key}><dt className="text-xs text-muted-foreground">{key.replaceAll('_', ' ')}</dt><dd className="text-lg">{display(value)}</dd></div>)}</dl><p className="text-sm text-muted-foreground">Compare your manual baseline with total supervision time and cost. Distinguish delivery failures from poor fit or conversation quality.</p></section><section className={panel}><h2 className="text-lg font-semibold">Work and evidence</h2><details><summary className="cursor-pointer text-sm">Queued work ({report?.jobs?.length ?? 0})</summary><pre className="overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(report?.jobs, null, 2)}</pre></details><details><summary className="cursor-pointer text-sm">Execution evidence</summary><pre className="overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(report?.events, null, 2)}</pre></details></section></div>}
  </main>;
}
